### ISSUE TITLE
Issue with xml.etree on some configuration

### ISSUE THREAD

**Issue by kutera** [kajala/django-jutil#2]
**Environment:** 
From django console, (python manage.py shell)
Python 3.5.2 (default, May 23 2018, 00:00:00)
[GCC 4.8.4] on linux

**Test Case**
>>> from xml.etree import ElementTree as ET
>>> from xml.etree.ElementTree import Element
>>> tag = {'test':'value'}
>>> el = ET.Element(tag)
>>> assert isinstance(el,Element)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AssertionError
>>> assert isinstance(el,ET.Element)
>>>

This error causes an assertion issue in line 216 in xml.py
    for tag, data in doc.items():
        el = ET.Element(tag)
        **assert isinstance(el, Element)**
        _xml_element_set_data_r(el, data, value_key, attribute_prefix)
        return el

I'll try to harmonize the import of xml.etree in my fork as workaround.
This error does not appear on my pycharm environnement, and does not appear on the test machine, but on the production machine yes ! Why ? I don't know.

**Comment by kajala** [comment]
Can you test the latest version? I unified the ElementTree.Element import usage in that xml.py

**Comment by kajala** [comment]
Ah you did a pull request already. :)

**Comment by kutera** [comment]
I had not the last release.
The release 2.2.2 works.  You can reject the pull request. 
Thanks !
